#!/bin/zsh

#
# Profile file
#
# Runs on login. Env vars not related to interactivity are set here.
#

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs
export EDITOR="helix"
export TERMINAL="alacritty"
export BROWSER="librewolf"

# To clean up the home directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Let qt5ct configure Qt5 applications
export QT_QPA_PLATFORMTHEME=qt5ct

# Start ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null
then
    ssh-agent -t 900 > "$XDG_CACHE_HOME/ssh-agent.env"
fi
if [ ! -f "$SSH_AUTH_SOCK" ]
then
    source "$XDG_CACHE_HOME/ssh-agent.env" > /dev/null
fi
