#!/bin/zsh

#
# Profile file
#
# Runs on login. Env vars not related to interactivity are set here.
#

# Default programs
export EDITOR="helix"
export VISUAL="$EDITOR"
export TERMINAL="alacritty"
export BROWSER="librewolf"

# To clean up the home directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"

# Let qt5ct configure Qt5 applications
export QT_QPA_PLATFORMTHEME=qt5ct

# Rust
export RUSTUP_HOME="$XDG_DATA_HOME/.rustup"
export CARGO_HOME="$XDG_DATA_HOME/.cargo"

# Node version manager (nvm)
export NVM_DIR="$XDG_DATA_HOME/.nvm"

# Add PATH, MANPATH, etc. for Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
# Add `~/.local/bin` to $PATH
#export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
# Add `$CARGO_HOME/bin` to $PATH
#export PATH="$PATH:$CARGO_HOME/bin"

# Kill ssh-agent if running
#pkill -u "$USER" ssh-agent
# Start ssh-agent
#ssh-agent -t 900 > "$XDG_RUNTIME_DIR/ssh-agent.env"
#if [ ! -f "$SSH_AUTH_SOCK" ]
#then
#    source "$XDG_RUNTIME_DIR/ssh-agent.env" > /dev/null
#fi
