#!/bin/zsh

#
# Profile file
#
# Runs on login. Env vars not related to interactivity are set here.
#

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs
export EDITOR="helix"
export TERMINAL="alacritty"
export BROWSER="brave"

# To clean up the home directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# If there is no graphical session yet and the login happened on the first tty, start wayland
if [ -z $WAYLAND_DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]
then
	exec sway
fi
