[[language]]
name = "java"
file-types = ["java"]
auto-format = true

[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "markdown"
scope = "source.markdown"
file-types = ["md"]
formatter = { command = "npx" , args = ["prettier", "--parser", "markdown", "--print-width", "70", "--prose-wrap", "always"] }
auto-format = true

#[[language]]
#name = "mdx"
#scope = "source.mdx"
#file-types = ["mdx"]
#roots = []
#formatter = { command = "npx" , args = ["prettier", "--parser", "mdx"] }
#auto-format = true

[[language]]
name = "vue"
scope = "source.vue"
file-types = ["vue"]
formatter = { command = "npx" , args = ["prettier", "--parser", "vue"] }
auto-format = true

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yaml", "yml"]
formatter = { command = "npx" , args = ["prettier", "--parser", "yaml"] }
auto-format = false

[[language]]
name = "html"
scope = "source.html"
file-types = ["html"]
formatter = { command = "npx" , args = ["prettier", "--parser", "html"] }
auto-format = true

[[language]]
name = "json"
scope = "source.json"
file-types = ["json"]
formatter = { command = "npx" , args = ["prettier", "--parser", "json"] }
auto-format = false

[[language]]
name = "css"
scope = "source.css"
file-types = ["css"]
formatter = { command = "npx" , args = ["prettier", "--parser", "css"] }
auto-format = true

[[language]]
name = "scss"
scope = "source.scss"
file-types = ["scss"]
formatter = { command = "npx" , args = ["prettier", "--parser", "scss"] }
auto-format = true

[[language]]
name = "less"
scope = "source.less"
file-types = ["less"]
roots = []
formatter = { command = "npx" , args = ["prettier", "--parser", "less"] }
auto-format = true

[[language]]
name = "javascript"
scope = "source.javascript"
file-types = ["js", "mjs"]
formatter = { command = "npx" , args = ["prettier", "--parser", "javascript"] }
auto-format = true

[[language]]
name = "jsx"
scope = "source.jsx"
file-types = ["jsx"]
formatter = { command = "npx" , args = ["prettier", "--parser", "javascript"] }
auto-format = true

[[language]]
name = "typescript"
scope = "source.typescript"
file-types = ["ts"]
formatter = { command = "npx" , args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
file-types = ["tsx"]
formatter = { command = "npx" , args = ["prettier", "--parser", "typescript"] }
auto-format = true
