[[language]]
name = "rust"
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "markdown" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "markdown"] }
auto-format = true

[[language]]
name = "mdx" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "mdx"] }
auto-format = true

[[language]]
name = "vue" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "vue"] }
auto-format = true

[[language]]
name = "yaml" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "yaml"] }
auto-format = true

[[language]]
name = "html" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "html"] }
auto-format = true

[[language]]
name = "json" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "json"] }
auto-format = true

[[language]]
name = "css" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "css"] }
auto-format = true

[[language]]
name = "scss" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "scss"] }
auto-format = true

[[language]]
name = "less" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "less"] }
auto-format = true

[[language]]
name = "javascript" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "javascript"] }
auto-format = true

[[language]]
name = "jsx" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "javascript"] }
auto-format = true

[[language]]
name = "typescript" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx" 
formatter = { command = "pnpm" , args = ["prettier", "--parser", "typescript"] }
auto-format = true
